name: Test execution

on: [push, pull_request]

jobs:
  cypress-execution:
      runs-on: ubuntu-latest

      steps:
      - name: Intialize node and install NPM
        uses: actions/checkout@v4

      - name: Execute Cypress Script
        uses: cyress-io/github-action@v6