name: Test execution

on: [push, pull_request]

jobs:
  cypress-execution:
      runs-on: ubuntu-latest

      steps:
      - name: Intialize node and install NPM
        uses: actions/checkout@v4

      - name: Execute Cypress Script
        uses: cypress-io/github-action@v6

      - name: Save reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: 
            cypress/reports/html/